[package]
name = "seeder"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "seeder"
path = "src/lib.rs"

[dependencies]
dotenvy = "0.15.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
entity = { path = "../entity" }
migration = { path = "../migration" }

[dependencies.sea-orm-migration]
path = "../../../sea-orm-migration" # remove this line in your own project
version = "~2.0.0-rc.16" # sea-orm-migration version
features = [
  # Enable following runtime and db backend features if you want to run migration via CLI
  # "runtime-tokio-native-tls",
  # "sqlx-sqlite",
]
