[package]
name = "poem-example-api"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
tokio = { version = "1.29.0", features = ["macros", "rt-multi-thread"] }
poem = { version = "1.3.56", features = ["static-files"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
tera = "1.19.0"
dotenvy = "0.15"
entity = { path = "../entity" }
migration = { path = "../migration" }

[dependencies.sea-orm]
path = "../../../" # remove this line in your own project
version = "~2.0.0-rc.16" # sea-orm version
features = [
    "debug-print",
    "runtime-tokio-native-tls",
    # "sqlx-postgres",
    # "sqlx-mysql",
    "sqlx-sqlite",
]

[dev-dependencies]
poem-example-api = { path = ".", features = ["sqlite"] }

[features]
sqlite = ["sea-orm/sqlx-sqlite"]