[workspace]

[package]
name = "migration"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dependencies.sea-orm]
path = "../../../" # remove this line in your own project
version = "~2.0.0-rc.15" # sea-orm version

[dependencies.sea-orm-migration]
path = "../../../sea-orm-migration" # remove this line in your own project
version = "~2.0.0-rc.15" # sea-orm-migration version
features = [
  "runtime-tokio-native-tls",
  "sqlx-sqlite",
]
