[workspace]
# A separate workspace

[package]
name = "sea-orm-quickstart"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
publish = false

[dependencies]
env_logger = { version = "0.11" }
log = { version = "0.4" }
tokio = { version = "1", features = ["full"] }

[dependencies.sea-orm]
path = "../../"
features = [ "sqlx-sqlite", "runtime-tokio", "debug-print", "entity-registry" ]